# Programming Problem 1: HMM for NER (30 points)
Welcome to the programming portion of the assignment! Each assignment throughout the semester will have a written portion and a programming portion. We will be using [Google Colab](https://colab.research.google.com/notebooks/intro.ipynb#recent=true), so if you have never used it before, take a quick look through this introduction: [Working with Google Colab](https://docs.google.com/document/d/1LlnXoOblXwW3YX-0yG_5seTXJsb3kRdMMRYqs8Qqum4/edit?usp=sharing).

### Writing Code
Look for the keyword "TODO" and fill in your code in the empty space.
Feel free to add and delete arguments in function signatures, but be careful that you might need to change them in function calls which are already present in the notebook.

### Data preprocessing

In this section we will write code to load data and build the dataset for Named Entity Recognition.

In [ ]:
import os
import re
import codecs

Write a function to load sentences.

In [ ]:
def zero_digits(s):
    """
    Replace all digits in a string with zeros.
    """
    return re.sub('\d', '0', s)

def load_sentences(path):
    """
    Load sentences. A line must contain at least a word and its tag.
    Sentences are separated by empty lines.
    """
    sentences = [] #Initialize an empty list to store the sentences
    sentence = [] # Initialize an empty list to store words in the current sentence
    for line in codecs.open(path, 'r', 'utf8'):  # "codecs.open": module in Python used for opening files with specific encodings
        line = zero_digits(line.rstrip()) # rstrip() method is used to remove any trailing whitespace from the line, and zero_digits replaces digits with zeros
        if not line: # the line is empty (not line), donc end of sentence.
            if len(sentence) > 0: # donc if the sentence list is not empty
                if 'DOCSTART' not in sentence[0][0]: # the first word in the sentence is not 'DOCSTART'
                    sentences.append(sentence) # donc the sentence is appended to the sentences list
                sentence = [] #  and the sentence list is reset
        else: # If the line is not empty
            word = line.split() # split the line into words
            assert len(word) >= 2 # ensures that each line contains at least a word and its tag
            sentence.append(word) # The word and its tag are appended to the sentence list
    if len(sentence) > 0:
        if 'DOCSTART' not in sentence[0][0]:
            sentences.append(sentence) # Append any remaining words in the last sentence to the sentences list
    return sentences #list of sentences -> each sentence is a list of word-tag pairs

Prepare the training/test data using the loaded sentences.

In [ ]:
def create_dico(item_list): # each sublist in item_list parameter is assumed to have items that need to be counted
    """
    Create a dictionary of items from a list of list of items.
    """
    assert type(item_list) is list #ensures ghat item_list is a list
    dico = {} # initialize an emty dictionary to store the count of items
    for items in item_list:
        for item in items:
            if item not in dico: # checks is the item is not repeated in the dicstionary
                dico[item] = 1 #new item donc add it's count by 1
            else:
                dico[item] += 1 #repeated item donc increment it count by 1
    return dico #returns a dictionary with the fount of items

In [ ]:
def create_mapping(dico): # -> takes a dictionary dico: keys-> items (words / tags), values -> their counts.
    """
    Create a mapping (item to ID / ID to item) from a dictionary.
    Items are ordered by decreasing frequency.
    """
    sorted_items = sorted(dico.items(), key=lambda x: (-x[1], x[0])) # sorts items in decreasing order of frequency
    id_to_item = {i: v[0] for i, v in enumerate(sorted_items) if v[1] > 2} # maps: keys as words/tags and values as counts: excluding el counts el olayela the rare / infrequent words
    item_to_id = {v: k for k, v in id_to_item.items()} # maps: keys as counts and values as words/tags
    return item_to_id, id_to_item

def word_mapping(sentences):
    """
    Create a dictionary and a mapping of words, sorted by frequency.
    """
    words = [[x[0] for x in s] for s in sentences] # extract kol words men el sentences
    dico = create_dico(words) #-> dictionary of word counts
    dico['<UNK>'] = 10000000 # special token that represents unknown words
    word_to_id, id_to_word = create_mapping(dico)
    print("Found %i unique words (%i in total)" % (
        len(dico), sum(len(x) for x in words))
    )
    return dico, word_to_id, id_to_word

def tag_mapping(sentences): # nafs el haga fel tags
    """
    Create a dictionary and a mapping of tags, sorted by frequency.
    """
    tags = [[word[-1] for word in s] for s in sentences]
    dico = create_dico(tags)
    tag_to_id, id_to_tag = create_mapping(dico)
    print("Found %i unique named entity tags" % len(dico))
    return dico, tag_to_id, id_to_tag

In [ ]:
def prepare_dataset(sentences, mode=None, word_to_id=None, tag_to_id=None):
    """
    Prepare the dataset. Return 'data', which is a list of lists of dictionaries containing:
        - words (strings)
        - word indexes
        - tag indexes
    """
    assert mode == 'train' or (mode == 'test' and word_to_id and tag_to_id) # assertion en el mode train aw test mode

    if mode=='train':
        word_dic, word_to_id, id_to_word = word_mapping(sentences)
        tag_dic, tag_to_id, id_to_tag = tag_mapping(sentences)

    def f(x): return x
    data = []
    for s in sentences:  # Iterates over each sentence
        str_words = [w[0] for w in s] # Extracts the words and tags from each sentence
        words = [word_to_id[f(w) if f(w) in word_to_id else '<UNK>'] # Converts each word ll id w law msh mawgouda -> <UNK>
                 for w in str_words]
        tags = [tag_to_id[w[-1]] for w in s] # nafs el kalam fel tags
        data.append({ #Appends dict (data)
            'str_words': str_words, #  the original words
            'words': words, # IDs lel words
            'tags': tags, # IDs el corresponding tags
        })

    if mode == 'train':
        return data, {'word_to_id':word_to_id, 'id_to_word':id_to_word, 'tag_to_id':tag_to_id, 'id_to_tag':id_to_tag}
    else:
        return data

### Hidden Markov Model
In this section, we will implement a bigram hidden markov model (HMM) that could perform two types of decoding: greedy decoding and viterbi decoding.


In [ ]:
import os
import re
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import OneHotEncoder
from scipy import sparse
import collections
import codecs

In [ ]:
class HMM(object):
    """
     HMM Model
    """
    def __init__(self, dic, decode_type):
        """
        Initialize the model.
        """

        self.num_words = len(dic['word_to_id'])
        self.num_tags = len(dic['tag_to_id'])

        self.initial_prob = np.ones([self.num_tags])
        self.transition_prob = np.ones([self.num_tags, self.num_tags])
        self.emission_prob = np.ones([self.num_tags, self.num_words])
        self.decode_type = decode_type

        return

    def train(self, corpus):
        """
        TODO: Train a bigram HMM model using MLE estimates.
        Complete the code to compute self,initial_prob, self.transition_prob and self.emission_prob appropriately.

        Args:
            corpus is a list of dictionaries of the form:
            {'str_words': str_words,   ### List of string words
            'words': words,            ### List of word IDs
            'tags': tags}              ### List of tag IDs
            All three lists above have length equal to the sentence length for each instance.

        """

        # Step 1: Compute initial_probs.
        # initial_prob[x]: the probability of tag x to be assigned to the first token in a sentence.
        self.initial_prob = np.zeros([self.num_tags])
        for sentence in corpus:
            # TODO: update self.initial_prob
            # (5 points)
            # START HERE
            self.initial_prob[sentence['tags'][0]] += 1
            # END HERE

        # Normarlize initial_prob to sum to 1
        self.initial_prob /= np.sum(self.initial_prob)

        # Step 2: Complete the code to compute transition_prob.
        # transition_prob[x][y]: the probability of tag y to appear after tag x.
        self.transition_prob = np.zeros([self.num_tags, self.num_tags])

        for sentence in corpus:
            tag = sentence['tags']
            for i in range(1, len(tag)):
                # TODO: update self.transition_prob
                # (5 points)
                # START HERE
                self.transition_prob[tag[i-1], tag[i]] += 1
                # END HERE

        # Normalize every row of transition_prob to sum to 1.
        for p in self.transition_prob:
            p /= np.sum(p)

        # Step 3: Complete the code to compute emission_prob
        # emission_prob[x][y]: the probability of word y to appear given tag x.
        # Note that for each sentence s in the corpus, word IDs are in s['words'].
        self.emission_prob = np.zeros([self.num_tags, self.num_words])
        for sentence in corpus:
          #for i in range(len(sentence['tags'])):
          for i in range(len(sentence['tags'])):
                # TODO: update self.emission_prob
                # (5 points)
                # START HERE
                self.emission_prob[sentence['tags'][i], sentence['words'][i]] += 1
                # END HERE

        # For every tag, normalize the emission_prob to sum to 1.
        for p in self.emission_prob:
            p /= np.sum(p)
        return

    def greedy_decode(self, sentence):
        """
        Decode a single sentence in Greedy fashion
        Return a list of tags.
        """
        tags = []

        init_scores = [self.initial_prob[t] * self.emission_prob[t][sentence[0]] for t in range(self.num_tags)]
        tags.append(np.argmax(init_scores))

        for w in sentence[1:]:
            scores = [self.transition_prob[tags[-1]][t] * self.emission_prob[t][w] for t in range(self.num_tags)]
            tags.append(np.argmax(scores))

        assert len(tags) == len(sentence)
        return tags

    def viterbi_decode(self, sentence):
        """
        TODO: Complete the code to decode a single sentence using the Viterbi algorithm.
        Args:
             sentence -- a list of ints that represents word IDs.
        Output:
             tags     -- a list of ints that represents the tags decoded from the input.
        """
        tags = []
        l = len(sentence)

        pi = self.initial_prob
        A = self.transition_prob
        O = self.emission_prob

        # Let M be the state matrix.
        # M[i,j]: most probable sequence of tags ending with tag j at the i-th token.
        M = np.zeros((l, self.num_tags))
        M[:,:] = float('-inf')

        # Use B to track the path to reach the most probable sequence.
        # B[i,j] is the tag of the (i-1)-th token in the most probable sequence ending with tag j at the i-th token.
        B = np.zeros((l, self.num_tags), 'int')

        # Compute the probability to assign each tag to the first token.
        M[0, :] = pi * O[:, sentence[0]]

        # Dynamic programming.
        for i in range(1, l):
            for j in range(self.num_tags):
                # TODO: Compute M[i, j] and B[i, j].
                # (10 points)
                # START HERE
                scores = M[i-1] + np.log(A[:, j]) + np.log(O[j, sentence[i]])
                M[i, j], B[i, j] = np.max(scores), np.argmax(scores)
                # END HERE

        # Extract the optimal sequence of tags from B.
        # Start from the last position, and iteratively find the tag of each position that results in the most probable tag sequence.
        tags.append(np.argmax(M[l-1,:]))
        for i in range(l-1, 0, -1):
            # TODO: Extract the tag of the (i-1)-th token that results in the most probable sequence of tags.
            # (5 points)
            # START HERE
            tags.append(B[i, tags[-1]])
            # END HERE
        tags.reverse()
        return tags

    def tag(self, sentence):
        """
        Tag a sentence using a trained HMM.
        """
        if self.decode_type == 'viterbi':
            return self.viterbi_decode(sentence)
        elif self.decode_type == 'greedy':
            return self.greedy_decode(sentence)
        else:
            raise ValueError("Unknown decoding type")

### Train and evaluate HMMs.
This section contains driver code for learning a HMM for named entity recognition on a training corpus and evaluating it on a test corpus.

In [ ]:
import os
import time
import codecs
import json
from tqdm import tqdm
import numpy as np
import collections
from sklearn.metrics import f1_score, confusion_matrix

Write a function to tag the test corpus with a trained model.

In [ ]:
def tag_corpus(model, test_corpus, output_file, dic):
    if output_file:
        f_output = codecs.open(output_file, 'w', 'utf-8')
    start = time.time()

    num_correct = 0.
    num_total = 0.
    y_pred=[]
    y_actual=[]
    print('Tagging...')
    for i, sentence in enumerate(tqdm(test_corpus)):
        tags = model.tag(sentence['words'])
        str_tags = [dic['id_to_tag'][t] for t in tags]
        y_pred.extend(tags)
        y_actual.extend(sentence['tags'])

        # Check accuracy.
        num_correct += np.sum(np.array(tags) == np.array(sentence['tags']))
        num_total += len([w for w in sentence['words']])

        if output_file:
            f_output.write('%s\n' % ' '.join('%s%s%s' % (w, '__', y)
                                             for w, y in zip(sentence['str_words'], str_tags)))

    print('---- %i lines tagged in %.4fs ----' % (len(test_corpus), time.time() - start))
    if output_file:
        f_output.close()

    print("Overall accuracy: %s\n" % (num_correct/num_total))
    return y_pred,y_actual

In [ ]:
def compute_score(y_pred,y_actual):
    A = confusion_matrix(y_actual, y_pred)
    f1 = f1_score(y_actual, y_pred,average=None)
    print("Confusion Matrix:\n", A)
    print("F-1 scores: ", f1)

Write a function to train and evalute the model.

In [ ]:
def runHiddenMarkovModel(train_corpus,
                         test_corpus,
                         dic,
                         decode_type,
                         output_file):
    # build and train the model
    model = HMM(dic, decode_type)
    model.train(train_corpus)

    print("Train results:")
    pred, real = tag_corpus(model, train_corpus, output_file, dic)

    print("Tags: ", dic['id_to_tag'])
    A = compute_score(pred,real)

    # test on validation
    print("\n-----------\nTest results:")
    pred, real = tag_corpus(model, test_corpus, output_file, dic)

    print("Tags: ", dic['id_to_tag'])
    A = compute_score(pred,real)

### Experiments

#### Load data

In [ ]:
# Download the dataset
!wget https://princeton-nlp.github.io/cos484/assignments/a2/eng.train
!wget https://princeton-nlp.github.io/cos484/assignments/a2/eng.val

train_file = 'eng.train'
test_file = 'eng.val'

# Load the training data
train_sentences = load_sentences(train_file)
train_corpus, dic = prepare_dataset(train_sentences, mode='train', word_to_id=None, tag_to_id=None)

# Load the testing data
test_sentences = load_sentences(test_file)
test_corpus = prepare_dataset(test_sentences, mode='test', word_to_id=dic['word_to_id'], tag_to_id=dic['tag_to_id'])

--2024-03-21 03:24:02--  https://princeton-nlp.github.io/cos484/assignments/a2/eng.train
Resolving princeton-nlp.github.io (princeton-nlp.github.io)... 185.199.111.153, 185.199.109.153, 185.199.110.153, ...
Connecting to princeton-nlp.github.io (princeton-nlp.github.io)|185.199.111.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3213441 (3.1M) [application/octet-stream]
Saving to: ‘eng.train.1’

eng.train.1         100%[===================>]   3.06M  --.-KB/s    in 0.07s   

2024-03-21 03:24:02 (45.4 MB/s) - ‘eng.train.1’ saved [3213441/3213441]

--2024-03-21 03:24:02--  https://princeton-nlp.github.io/cos484/assignments/a2/eng.val
Resolving princeton-nlp.github.io (princeton-nlp.github.io)... 185.199.111.153, 185.199.109.153, 185.199.110.153, ...
Connecting to princeton-nlp.github.io (princeton-nlp.github.io)|185.199.111.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 774436 (756K) [application/octet-stream]
Saving to: ‘eng.v

In [ ]:
num_lines_to_display = 5

# Read the first few lines of the training file
print("Training Sample:")
with open(train_file, 'r', encoding='utf-8') as file:
    for _ in range(num_lines_to_display):
        line = file.readline().strip()
        if line:
            print(line)

# Read the first few lines of the test file
print("Test Sample:")
with open(test_file, 'r', encoding='utf-8') as file:
    for _ in range(num_lines_to_display):
        line = file.readline().strip()
        if line:
            print(line)

Training Sample:
EU NNP I-NP ORG
rejects VBZ I-VP O
German JJ I-NP MISC
call NN I-NP O
to TO I-VP O
Test Sample:
CRICKET NNP I-NP O
- : O O
LEICESTERSHIRE NNP I-NP ORG
TAKE NNP I-NP O
OVER IN I-PP O


#### Experiment with an HMM with greedy decoding for Problem 2(a)

In [ ]:
runHiddenMarkovModel(
    train_corpus = train_corpus,
    test_corpus = test_corpus,
    dic = dic,
    decode_type = 'greedy',
    output_file = None
)

Train results:
Tagging...


100%|██████████| 14041/14041 [00:02<00:00, 5840.47it/s]


---- 14041 lines tagged in 2.4106s ----
Overall accuracy: 0.9544742438157164

Tags:  {0: 'O', 1: 'PER', 2: 'ORG', 3: 'LOC', 4: 'MISC'}
Confusion Matrix:
 [[168060    135   1233     48    102]
 [  1999   8628    456     39      6]
 [  1632     98   7291    731    273]
 [   741     49    567   6886     54]
 [   665     32    206    204   3486]]
F-1 scores:  [0.98087109 0.85979073 0.73728385 0.84986115 0.81888654]

-----------
Test results:
Tagging...


100%|██████████| 3490/3490 [00:00<00:00, 6123.10it/s]


---- 3490 lines tagged in 0.5792s ----
Overall accuracy: 0.9241331540561464

Tags:  {0: 'O', 1: 'PER', 2: 'ORG', 3: 'LOC', 4: 'MISC'}
Confusion Matrix:
 [[40558    17   543    17    29]
 [ 1105  1294   267    16     8]
 [  606    30  1382   176    56]
 [  249    15   215  1478    18]
 [  233     8    79    37   650]]
F-1 scores:  [0.96664482 0.63838185 0.58361486 0.7991349  0.73529412]


#### Experiment with an HMM with viterbi decoding for Problem 2(b)

In [ ]:
runHiddenMarkovModel(
    train_corpus = train_corpus,
    test_corpus = test_corpus,
    dic = dic,
    decode_type = 'viterbi',
    output_file = None
)

Train results:
Tagging...


  0%|          | 0/14041 [00:00<?, ?it/s]<ipython-input-13-a1eb62f844e3>:132: RuntimeWarning: divide by zero encountered in log
  scores = M[i-1] + np.log(A[:, j]) + np.log(O[j, sentence[i]])
100%|██████████| 14041/14041 [00:16<00:00, 846.23it/s]


---- 14041 lines tagged in 16.6008s ----
Overall accuracy: 0.9362050083242888

Tags:  {0: 'O', 1: 'PER', 2: 'ORG', 3: 'LOC', 4: 'MISC'}
Confusion Matrix:
 [[165769   2279    881    284    365]
 [  1845   9188     63     26      6]
 [  2493    602   6464    350    116]
 [  1979    153    396   5715     54]
 [   824    133     84     57   3495]]
F-1 scores:  [0.96802808 0.78252353 0.72171049 0.7760201  0.8100591 ]

-----------
Test results:
Tagging...


  0%|          | 0/3490 [00:00<?, ?it/s]<ipython-input-13-a1eb62f844e3>:132: RuntimeWarning: divide by zero encountered in log
  scores = M[i-1] + np.log(A[:, j]) + np.log(O[j, sentence[i]])
100%|██████████| 3490/3490 [00:03<00:00, 916.08it/s] 


---- 3490 lines tagged in 3.8198s ----
Overall accuracy: 0.9110133235545776

Tags:  {0: 'O', 1: 'PER', 2: 'ORG', 3: 'LOC', 4: 'MISC'}
Confusion Matrix:
 [[39818   985   193    62   106]
 [  716  1918    38    10     8]
 [  813   177  1107   109    44]
 [  530    74   102  1246    23]
 [  264    66    36    12   629]]
F-1 scores:  [0.95595703 0.64906937 0.5942029  0.72993556 0.69235003]
